### ISSUE TITLE
Problem about Rotation 90 degrees with bounding box

### ISSUE THREAD

**Issue by Demo5284** [aleju/imgaug#602]
Thank you and this useful tool. It is easy to augment my image. However, there is a small problem that bothers me.

After running iaa.Rot90(k=1) and checking the bounding box, I got a wired result of bounding box, and iaa.Affine(rotate=90) was the same.  I also tried iaa.Rot90(k=3) and it looked great. 
![螢幕快照 2020-02-01 下午7 06 30](https://user-images.githubusercontent.com/60341993/73591162-2df00580-4526-11ea-8593-60c31e6dbe44.png)

How could I solve this?

p.s. I run another image with iaa.Rot90(k=1) and it doesn't have this mistake. It seems to have this problem with the example above.

**Comment by aleju** [comment]
Are you using the version from pypi (0.3.0) or the latest version from github (`pip install git+https://github.com/aleju/imgaug.git`)? I think in the 0.3.0 release there were bugs related to bounding boxes where the augmentation was based only on the top-left and bottom-right corners, which could cause such issues in the case of rotations. These bugs are already fixed in master.

**Comment by Demo5284** [comment]
I use Anaconda and use the command "conda install imgaug", and the version of imgaug is 0.3.0. So I need to got the "master"????

**Comment by aleju** [comment]
Yes, right now you need the version corresponding to the latest commit on github (branch "master").
I think `pip install git+https://github.com/aleju/imgaug.git` within the anaconda environment should replace the library, even if it was installed via `conda install <name>`, though I'm not sure if I have ever tried that.

The next release will probably be beginning of next week, which will also fix the issue.

**Comment by Demo5284** [comment]
Ha ha, I used this command and updated to the latest version, but it still have the same problem. It's OK. BTW, Is there probably the same problem about Rot90(k=3)?

**Comment by aleju** [comment]
Hm, I think usually both `k=1` and `k=3` should work. If it doesn't work for you, then both will probably fail.

Can you please try `import imgaug; print(hasattr(imgaug.augmenters, "WithPolarWarping"))` somewhere in your script? It should print `True` if you are running on the latest version. If it is `False`, it still uses the pypi release.
You could also try `pip uninstall imgaug; pip install git+https://github.com/aleju/imgaug.git`, maybe it needs an explicit uninstall.

Here is a quick example debug image from latest master with `Rot90(k=0)`, `Rot90(k=1)`, `Rot90(k=2)` and `Rot90(k=3)` (row 1 to 4):

![image](https://user-images.githubusercontent.com/11698516/73593971-d2b01a00-4509-11ea-8140-539f8a10101e.png)

Bounding boxes on the right. Seems like it works. Or are you currently observing this on other augmenters than `Rot90`?

**Comment by Demo5284** [comment]
OKay, I tried the command `import imgaug; print(hasattr(imgaug.augmenters, "WithPolarWarping"))` and then it printed `True`, so I thought the version I used was the latest version.

Now I'm observing another augmenters you coded. 

Sorry to bother you so many times , many thanks.

**Comment by aleju** [comment]
> Now I'm observing another augmenters you coded.
> Sorry to bother you so many times , many thanks.

So you mean that it works as expected now, or are the bounding boxes still looking malformed?

**Comment by Demo5284** [comment]
Bounding boxes still looked malformed.    ( ´▽｀)

**Comment by aleju** [comment]
Hm, if it still doesn't work with the newest version then I'm not really sure what the cause of the problem is. I tried again with `Rot90` and `Affine(rotation=<multiples of 90>)` and both cases seemed to work fine. I guess that is what you used?
If you used `BoundingBoxesOnImage`, you could recheck if the `shape` parameter matches the image shape, but errors there should usually not cause these kinds of outputs.

See example script and images below.

```python
import imgaug as ia
import imgaug.augmenters as iaa
import imgaug.parameters as iap


def main():
    test_rot90()
    test_affine_rot90()


def test_rot90():
    print("Rot90")
    batch = create_batch()
    aug = iaa.Rot90(k=iap.DeterministicList([0, 1, 2, 3]))
    batch_aug = aug.augment_batch_(batch)
    ia.imshow(draw_debug_images_batch(batch_aug))


def test_affine_rot90():
    print("Affine rotation=90")
    batch = create_batch()
    aug = iaa.Affine(rotate=iap.DeterministicList([0, 90, 180, 270]))
    batch_aug = aug.augment_batch_(batch)
    ia.imshow(draw_debug_images_batch(batch_aug))


def draw_debug_images_batch(batch):
    return iaa.draw_debug_image(
        images=batch.images_aug,
        heatmaps=batch.heatmaps_aug,
        segmentation_maps=batch.segmentation_maps_aug,
        keypoints=batch.keypoints_aug,
        bounding_boxes=batch.bounding_boxes_aug,
        polygons=batch.polygons_aug
    )


def create_batch():
    batch = ia.Batch(
        images=(
            [ia.quokka((128, 128))] * 4
            + [ia.quokka((128, 256))] * 4
        ),
        bounding_boxes=(
            [ia.quokka_bounding_boxes((128, 128))] * 4
            + [ia.quokka_bounding_boxes((128, 256))] * 4
        )
    )
    return batch


if __name__ == "__main__":
    main()

```

![rot90-2](https://user-images.githubusercontent.com/11698516/73608385-97255680-45c2-11ea-9476-aae4b0f71758.png)

![affine_rot90_2](https://user-images.githubusercontent.com/11698516/73608379-8d035800-45c2-11ea-9a69-64a4659739d1.png)

**Comment by Demo5284** [comment]
Thank you very much. 
I found my mistake. There are something wrong in my code.
After changing this mistake, it show me the best what I need. 
Sorry to bother you so many times , many thanks.
